const assert=require('node:assert/strict');
const M=require('./dist/core.js');
assert.deepEqual(M.parse('ข้าว 50'),{note:'ข้าว',amount:50});
assert.deepEqual(M.parse('เครื่องมือช่าง 1,200.50 บาท'),{note:'เครื่องมือช่าง',amount:1200.5});
for(const s of ['ข้าว','ข้าว 0','ข้าว 50 หมู 100','50'])assert.equal(M.parse(s),null);
assert.equal(M.suggest('เครื่องมือช่าง'),'เครื่องมือ');
assert.equal(M.suggest('ไม่รู้'),'รอจัดหมวด');
const state={accounts:[{id:'cash',opening:1000},{id:'bank',opening:500}],entries:[{account:'cash',type:'expense',amount:50},{account:'cash',type:'lend',amount:200},{account:'bank',type:'income',amount:100},{account:'bank',type:'repay',amount:80}]};
assert.equal(M.balance(state,'cash'),750);assert.equal(M.balance(state,'bank'),680);assert.equal(M.total(state),1430);assert.equal(M.debt(state),120);
state.entries.splice(0,1);assert.equal(M.balance(state,'cash'),800);
console.log('Passed: parsing, category suggestions, account balances, debt, deletion recalculation');
const accounts={accounts:[{id:'a',opening:10},{id:'b',opening:0},{id:'c',opening:0},{id:'d',opening:0}],entries:[{account:'c',type:'expense',amount:2}]};
assert.equal(M.removeAccount(accounts,'b'),'deleted');
assert.equal(M.removeAccount(accounts,'a'),'archived');
assert.equal(M.total(accounts),8);
assert.equal(M.removeAccount(accounts,'c'),'archived');
assert.equal(M.removeAccount(accounts,'d'),'last');
assert.equal(accounts.entries.length,1);
accounts.accounts.find(a=>a.id==='a').archived=false;
assert.equal(M.activeAccounts(accounts).length,2);
console.log('Passed: account deletion, archiving, retained balances and history, last-account guard, restoring');
