const assert=require('node:assert/strict');
const M=require('./dist/core.js');
assert.deepEqual(M.parse('ข้าว 50'),{note:'ข้าว',amount:50});
assert.deepEqual(M.parse('เครื่องมือช่าง 1,200.50 บาท'),{note:'เครื่องมือช่าง',amount:1200.5});
for(const s of ['ข้าว','ข้าว 0','ข้าว 50 หมู 100','50'])assert.equal(M.parse(s),null);
assert.equal(M.suggest('เครื่องมือช่าง'),'เครื่องมือ');
assert.equal(M.suggest('ไม่รู้'),'รอจัดหมวด');
const state={accounts:[{id:'cash',opening:1000},{id:'bank',opening:500}],entries:[{account:'cash',type:'expense',amount:50},{account:'cash',type:'lend',amount:200},{account:'bank',type:'income',amount:100},{account:'bank',type:'repay',amount:80}]};
assert.equal(M.balance(state,'cash'),750);assert.equal(M.balance(state,'bank'),680);assert.equal(M.total(state),1430);assert.equal(M.debt(state),120);
state.entries.splice(0,1);assert.equal(M.balance(state,'cash'),800);
console.log('Passed: parsing, category suggestions, account balances, debt, deletion recalculation');
const accounts={accounts:[{id:'a',opening:10},{id:'b',opening:0},{id:'c',opening:0},{id:'d',opening:0}],entries:[{account:'c',type:'expense',amount:2}]};
assert.equal(M.removeAccount(accounts,'b'),'deleted');
assert.equal(M.removeAccount(accounts,'a'),'archived');
assert.equal(M.total(accounts),8);
assert.equal(M.removeAccount(accounts,'c'),'archived');
assert.equal(M.removeAccount(accounts,'d'),'last');
assert.equal(accounts.entries.length,1);
accounts.accounts.find(a=>a.id==='a').archived=false;
assert.equal(M.activeAccounts(accounts).length,2);
console.log('Passed: account deletion, archiving, retained balances and history, last-account guard, restoring');

const transfers={accounts:[{id:'cash',kind:'wallet',opening:1000},{id:'bank',kind:'wallet',opening:0},{id:'friend',kind:'borrower',opening:0}],entries:[]};
const movement={id:'t1',account:'cash',toAccount:'bank',type:'transfer',amount:100.25};
assert.equal(M.validateTransfer(transfers,movement),'');
transfers.entries.push(movement);
assert.equal(M.balance(transfers,'cash'),899.75);
assert.equal(M.balance(transfers,'bank'),100.25);
assert.equal(M.total(transfers),1000);
const loan={id:'t2',account:'cash',toAccount:'friend',type:'transfer',amount:200};
transfers.entries.push(loan);
assert.equal(M.balance(transfers,'friend'),200);
assert.equal(M.debt(transfers),200);
assert.equal(M.total(transfers),800);
const repayment={id:'t3',account:'friend',toAccount:'bank',type:'transfer',amount:80};
assert.equal(M.validateTransfer(transfers,repayment),'');
transfers.entries.push(repayment);
assert.equal(M.debt(transfers),120);
assert.equal(M.total(transfers),880);
assert.equal(M.validateTransfer(transfers,{...repayment,id:'over',amount:121}),'');
assert.notEqual(M.validateTransfer(transfers,{...movement,toAccount:'cash'}),'');
assert.equal(M.validateTransfer(transfers,{...loan,amount:50},'t2'),'');
assert.equal(M.validateTransfer(transfers,{...loan,amount:150},'t2'),'');
assert.equal(M.removeAccount(transfers,'bank'),'archived');
assert.equal(transfers.entries.length,3);
const legacy={accounts:[{id:'a',opening:1000},{id:'b',opening:0}],entries:[{id:'l',account:'a',type:'lend',amount:200},{id:'r',account:'b',type:'repay',amount:50}]};
const migrated=M.migrate(legacy);
assert.equal(legacy.entries[0].type,'lend');
assert.equal(M.total(migrated),M.total(legacy));
assert.equal(M.debt(migrated),M.debt(legacy));
assert.equal(migrated.entries[0].id,'l');
assert.equal(migrated.entries[1].id,'r');
assert.deepEqual(M.migrate(migrated),migrated);
assert.equal(M.wallets(migrated).length,2);
console.log('Passed: transfers, per-borrower debt, repayment/edit guards, destination history, migration and idempotence');
const appSource=require('node:fs').readFileSync(require('node:path').join(__dirname,'dist/app.js'),'utf8');
const freshState=require('node:vm').runInNewContext('('+appSource.match(/const initial=\(\)=>(.*);/)[1]+')',{Money:M});
assert.equal(freshState.accounts.length,0);assert.equal(freshState.entries.length,0);assert.equal(freshState.budget,0);
assert.equal(M.total(M.migrate(freshState)),0);
const closeHandler=appSource.match(/\$\('transferDialog'\)\.addEventListener\('close',\(\)=>\{([\s\S]*?)\n\}\);/);
assert.ok(closeHandler,'transfer dialog must handle every close path');
const typeButtons=['expense','income','transfer'].map(value=>({dataset:{type:value},classList:{toggle(name,on){this.selected=on}},setAttribute(name,value){this[name]=value}}));
const closeCategory={innerHTML:''};
const closeContext={type:'transfer',manualCategory:true,$(){return closeCategory},options(){return 'expense-options'},suggest(){},document:{querySelectorAll(){return typeButtons}}};
require('node:vm').runInNewContext(closeHandler[1],closeContext);
assert.equal(closeContext.type,'expense');
assert.equal(closeCategory.innerHTML,'expense-options');
assert.equal(closeContext.manualCategory,false);
assert.deepEqual(typeButtons.map(b=>b.classList.selected),[true,false,false]);
assert.deepEqual(typeButtons.map(b=>b['aria-pressed']),['true','false','false']);
console.log('Passed: closing transfer resets type, selection and accessibility to expense');
const categoryState=M.migrate({budget:0,accounts:[{id:'cash',opening:500}],entries:[{id:'food',account:'cash',amount:50,type:'expense',category:'อาหาร'},{id:'old',account:'cash',amount:10,type:'expense',category:'หมวดเก่า'}]});
const categoryTotal=M.total(categoryState);
assert.ok(M.categories(categoryState).includes('หมวดเก่า'));
assert.equal(M.saveCategory(categoryState,'สัตว์เลี้ยง'),'');
assert.ok(M.categories(categoryState).includes('สัตว์เลี้ยง'));
assert.equal(M.saveCategory(categoryState,'อาหารและเครื่องดื่ม','อาหาร'),'');
assert.equal(categoryState.entries[0].category,'อาหารและเครื่องดื่ม');
assert.equal(M.suggestCategory(categoryState,'กาแฟ'),'อาหารและเครื่องดื่ม');
assert.equal(M.saveCategory(categoryState,'กินดื่ม','อาหารและเครื่องดื่ม'),'');
assert.equal(M.suggestCategory(categoryState,'ข้าว'),'กินดื่ม');
assert.equal(M.total(categoryState),categoryTotal);
assert.ok(M.saveCategory(categoryState,'สัตว์เลี้ยง'));
assert.ok(M.saveCategory(categoryState,' '));
assert.ok(M.saveCategory(categoryState,'โอน'));
assert.ok(M.saveCategory(categoryState,'ใหม่','รอจัดหมวด'));
assert.deepEqual(M.migrate(JSON.parse(JSON.stringify(categoryState))),categoryState);
assert.equal(M.suggestCategory(JSON.parse(JSON.stringify(categoryState)),'กาแฟ'),'กินดื่ม');
console.log('Passed: category addition, rename, legacy category retention, suggestion aliases, validation and persistence');
const grouping=M.migrate({budget:300,accounts:[{id:'c',name:'เงินสด',opening:100},{id:'b',name:'MyMo',opening:200},{id:'s',name:'เงินเก็บ(make by k bank)',opening:300},{id:'e',name:'TrueMoney wallet',opening:40},{id:'p',name:'คนหนึ่ง',kind:'borrower',opening:50},{id:'n',name:'อีกคน',kind:'borrower',opening:-20},{id:'custom',name:'ธนาคารที่ใช้เก็บเงิน',kind:'wallet',group:'savings',opening:10},{id:'hide',name:'ซ่อน',opening:5,archived:true}],entries:[]});
assert.equal(M.accountGroup(grouping.accounts[0]),'cash');
assert.equal(M.accountGroup(grouping.accounts[1]),'bank');
assert.equal(M.accountGroup(grouping.accounts[2]),'savings');
assert.equal(M.accountGroup(grouping.accounts[3]),'ewallet');
assert.equal(M.accountGroup(grouping.accounts[6]),'savings');
assert.equal(M.accountGroup({name:'คน',kind:'borrower',group:'bank'}),'bank');
const accountGroups=M.groupedAccounts(grouping);
assert.equal(accountGroups.flatMap(g=>g.accounts).length,grouping.accounts.length);
assert.equal(new Set(accountGroups.flatMap(g=>g.accounts.map(a=>a.id))).size,grouping.accounts.length);
assert.equal(accountGroups.find(g=>g.id==='savings').total,310);
assert.equal(accountGroups.find(g=>g.id==='debt').receivable,50);
assert.equal(accountGroups.find(g=>g.id==='debt').payable,20);
assert.equal(accountGroups.at(-1).id,'archived');
const groupTotal=M.total(grouping);grouping.accounts[0].group='other';assert.equal(M.total(grouping),groupTotal);
assert.equal(M.accountGroup(grouping.accounts[0]),'other');
assert.deepEqual(M.migrate(grouping),grouping);
console.log('Passed: account grouping, manual override, signed debt summaries, archived accounts, idempotent migration and unchanged balances');
const managed=structuredClone(grouping),beforeManaged={total:M.total(grouping),debt:M.debt(grouping),owed:M.owed(grouping)};
assert.equal(M.saveGroup(managed,'เงินที่ให้ยืม','debt'),'');
assert.equal(M.groups(managed).find(g=>g.id==='debt').label,'เงินที่ให้ยืม');
assert.equal(M.saveGroup(managed,'โปรเจกต์',null,'project'),'');
assert.ok(M.saveGroup(managed,'โปรเจกต์',null,'duplicate'));
assert.ok(M.saveGroup(managed,'','bank'));
assert.equal(M.removeGroup(managed,'debt'),true);
assert.equal(managed.accounts.find(a=>a.id==='p').group,'ungrouped');
assert.equal(managed.accounts.find(a=>a.id==='n').group,'ungrouped');
assert.equal(M.groups(M.migrate(managed)).some(g=>g.id==='debt'),false);
assert.equal(M.accountGroup({kind:'borrower',name:'new'},managed),'ungrouped');
assert.equal(M.removeGroup(managed,'ungrouped'),false);
assert.deepEqual({total:M.total(managed),debt:M.debt(managed),owed:M.owed(managed)},beforeManaged);
assert.equal(M.deleteBorrower(managed,'p'),true);
assert.equal(M.debt(managed),0);assert.equal(M.total(managed),beforeManaged.total);
assert.equal(M.groupedAccounts(managed).flatMap(g=>g.accounts).some(a=>a.id==='p'),false);
assert.equal(M.activeAccounts(managed).some(a=>a.id==='p'),false);
assert.equal(M.restoreBorrower(managed,'p'),true);
assert.equal(M.debt(managed),beforeManaged.debt);
assert.equal(managed.accounts.find(a=>a.id==='p').group,'ungrouped');
assert.equal(M.deleteBorrower(managed,'c'),false);
const withHistory=M.migrate({budget:0,accounts:[{id:'w',kind:'wallet',opening:100},{id:'p',kind:'borrower',opening:0}],entries:[{id:'lend',account:'w',toAccount:'p',type:'transfer',amount:30}]});
M.deleteBorrower(withHistory,'p');assert.equal(M.balance(withHistory,'w'),70);assert.equal(withHistory.entries.length,1);
assert.equal(M.debt(withHistory),0);M.restoreBorrower(withHistory,'p');assert.equal(M.debt(withHistory),30);
assert.deepEqual(M.migrate(managed),managed);
console.log('Passed: custom group rename/add/delete, no revived groups, ungrouped fallback, borrower trash/restore and retained cash/history');
const typedCategories=M.migrate({budget:0,accounts:[],entries:[{type:'income',category:'ขายของ',amount:50},{type:'expense',category:'เดินทาง',amount:20}]});
assert.ok(M.categories(typedCategories,'income').includes('ขายของ'));
assert.ok(!M.categories(typedCategories,'expense').includes('ขายของ'));
assert.ok(M.categories(typedCategories,'expense').includes('เดินทาง'));
assert.ok(!M.categories(typedCategories,'income').includes('อาหาร'));
assert.ok(!M.categories(typedCategories,'expense').includes('เงินเดือน'));
assert.equal(M.saveCategory(typedCategories,'เงินพิเศษ',null,'income'),'');
assert.ok(!M.categories(typedCategories,'expense').includes('เงินพิเศษ'));
assert.equal(M.saveCategory(typedCategories,'ค่าจ้าง','เงินเดือน','income'),'');
assert.ok(M.categories(typedCategories,'income').includes('ค่าจ้าง'));
assert.ok(!M.categories(typedCategories).includes('เงินเดือน'));
assert.equal(M.suggestCategory(typedCategories,'ข้าว','income'),'รอจัดหมวด');
assert.deepEqual(M.migrate(typedCategories),typedCategories);
console.log('Passed: income/expense category filtering, historical categories, typed addition/rename and persistence');
